### ISSUE TITLE
MAZ cell 1 map immediately completes the "Don't run a map" Quest

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#106]
![image](https://user-images.githubusercontent.com/51026936/182729913-fffb954c-0e6a-4855-a550-80df542e2e05.png)

Save:
[Trimps Save P592 198 U2 Z79.txt](https://github.com/Trimps/bug-tracker/files/9255585/Trimps.Save.P592.198.U2.Z79.txt)

**Comment by Trimps** [comment]
Fixed on 5.9.0 test server, thanks!
