### ISSUE TITLE
Post U1 z200 Void Map loot/difficulty increase applies to all existing maps in the map chamber

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#109]
**Describe the bug**
The new U1 z200 void map difficulty/loot increase (`buffVoidMaps200` function) erroneously applies to every map

**To Reproduce**
1. Have some maps
2. Get beyond zone 200
3. All your maps have +100% loot and difficulty

**Screenshots**

Before
![image](https://user-images.githubusercontent.com/51026936/183263077-7266e305-7377-4bda-8255-7b75647cb978.png)

After
![image](https://user-images.githubusercontent.com/51026936/183263081-21b0f2b9-7592-4e92-bfac-d705d5079d0c.png)

**Comment by Trimps** [comment]
This has been hotfixed and is now live, thank you!
