### ISSUE TITLE
U2 z201 erroneously claims a new perk is unlocked

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#110]
![image](https://user-images.githubusercontent.com/51026936/183263916-d8ea09b4-06c8-41b6-9722-7a4163268753.png)

Z201 was the trigger for Smithology before Smithless was introduced, and the message from z201 about a new perk was not taken out.

**Comment by Trimps** [comment]
Fixed on the 5.9.0 Test Server, thanks!
