### ISSUE TITLE
Bone Trader bone portal does not update unless you manually end daily

### ISSUE THREAD

**Issue by RacinanteOpus** [Trimps/bug-tracker#111]
When completing a daily, if you end the daily and then portal, the bone trader updates with the total radon portal correctly.  If you portal without manually ending the daily, the bone trader does not update.

**To Reproduce**
Duplicate your end of daily run, so you have it at the same moment pre-portal.
In one copy, end the daily, then portal.  Check the bone trader bone portal amount.  This number will be updated by the new radon amount.
In the other copy, portal.  Check the bone trader bone portal amount.  This number will be the same as it was before.

**Expected behavior**
Expected both methods of ending the daily and portalling would update the bone trader.

Save in the bugs and ideas section on Discord.

Ubuntu Linux, Firefox
Web version

**Comment by RacinanteOpus** [comment]
This is my wife's save before ending the daily and can be used to demonstrate the bug.
[Bone Portal Daily Bug.txt](https://github.com/Trimps/bug-tracker/files/9276118/Bone.Portal.Daily.Bug.txt)

**Comment by Trimps** [comment]
Fixed on 5.9.0 Test Server, thanks!
