### ISSUE TITLE
Setting AutoJob Farmer to 0 causes major UI errors.

### ISSUE THREAD

**Issue by GodNooNoo** [Trimps/bug-tracker#118]
**Describe the bug**
By setting the ratio value for Farmer to 0 makes the UI go all wonky, miners and scientists shows as infinity, metal and science production stops showing, the entire breeding section stops working. The ratio also shows as 1 even if set to 0.

**To Reproduce**
1. Toggle AutoJobs off.
2. Portal
3. Set the ratio for Farmers to 0.
4. Toggle AutoJobs on.
5. Press fight.
7. Upon encountering the first territory bonus, observe the error.

Alternative method.
1. Set the ratio for Farmers to 0.
2. Portal
3. Press fight
4. Upon encountering the first territory bonus, observe the error.

**Expected behavior**
For the UI to not go all wonky wonky. Possibly not allowing 0 as input or having 0 work correctly.

**Environment (please complete the following information):**
 - Windows
 - Web and Steam
 - Chrome

**Additional context**
It is only a visual bug and goes away when doing a refresh. 

**Hiring at least 1 Farmer before encountering the territory bonus makes the game work correctly.** Guessing AutoJobs ends up dividing by 0 when calculating some ratio, which causes miners and scientists to be set to infinity.

When setting the ratio to 0 the UI still shows is as 1 after pressing apply and opening AutoJobs again. However, the validation check for the input specifically allows 0 to be set. Dependent on how the bug is solved the UI and validation should match up.

**Comment by Trimps** [comment]
Fixed with 5.8.1, thanks!
