### ISSUE TITLE
Add an additional notification if a player is about to Portal without starting a challenge

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#12]
**Is your feature request related to a problem? Please describe.**
Players sometimes accidentally fail to start a challenge when portaling, which feels very bad in the early game when it takes a long time to reach DoA again.

**Describe the solution you'd like**
1) Additional confirmation popup before portaling without a challenge.
2) Add a new setting to disable this functionality.
3) The setting should be enabled by default.

**Comment by Trimps** [comment]
Added to 5.7.2!
