### ISSUE TITLE
Change 0.5% to 1.005 on description of Scientist V

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#120]
> Choose your upgrades wisely! Clearing 'The Block' (11) with this challenge active will cause you to permanently increase all Helium found by 0.5% to the power of your current Zone number.

> You have completed the Scientist Challenge! From now on, you'll permanently increase all Helium found by 0.5% to the power of your current Zone number

//// change to ////

> Choose your upgrades wisely! Clearing 'The Block' (11) with this challenge active will cause you to permanently increase all Helium found by 1.005 to the power of your current Zone number.

> You have completed the Scientist Challenge! From now on, you'll permanently increase all Helium found by 1.005 to the power of your current Zone number

**Comment by Trimps** [comment]
Updated to "found by 0.5% per zone (compounding)." on the 5.9.0 Test Server, thanks!
