### ISSUE TITLE
12 Errors in Settings & AutoFight

### ISSUE THREAD

**Issue by bddbdwbej** [Trimps/bug-tracker#126]
**Missing period, missing posessive(?) in AutoFight tooltip**

![image](https://user-images.githubusercontent.com/106824371/186774411-9e859d31-3704-4314-8ce9-e051d089c1da.png)

Missing period (after overcrowded) is inconsistent with most other tooltips.

In all instances I can think of, Trimps are referred to as 'your Trimps' instead of 'the Trimps'. Perhaps conception of them shifted after writing this (it is one of the earliest mechanics). It's up to your judgement if this wording should be changed for consistency with the rest of the game.

---

**Missing period in Auto Saving tooltip**
Category: General

![image](https://user-images.githubusercontent.com/106824371/186773633-cce009a6-b2e6-4108-9c89-87807f830621.png)

Missing period is inconsistent with most other tooltips.

---

**Missing period & strange capitalization in Dimensional Generator Config tooltip**
Category: General

![image](https://user-images.githubusercontent.com/106824371/186774010-4afe6f96-c0c0-4e0e-8b65-1bd1adfceb72.png)

Missing period is inconsistent with most other tooltips.

"**Rest of The Settings**" seems like it should be changed to "**rest of the settings**". I'm not sure why "**Rest**" and "**The**" are capitalized, and "**Settings**" is iffy but I believe it should be lowercase if not referring to the Settings menu as a whole. As always, up to your judgement.

---

**Inconsistent capitalization in Equipment Highlighting tooltip**
Category: Quality of Life

![image](https://user-images.githubusercontent.com/106824371/186781567-a72716e5-1735-43d8-ba6f-ca3621a8c67a.png)

"**Highlight all Tiers**" should be changed to "**Highlight All Tiers**" in the tooltip and button display.

---

**Inconsistent capitalization & continuity error in Tier First/Equip First tooltip**
Category: Quality of Life

![image](https://user-images.githubusercontent.com/106824371/186770638-10c2b942-a094-4f07-817e-17579e0bdc35.png)

"**Tier first**" and "**Equip first**" should be changed to "**Tier First**" and "**Equip First**" to match up with the button display and tooltip header.

If Slow has been completed, "(Greatsword II -> Breastplate II -> Shield III)" should be changed to "(Arbalest II -> Gambeson II -> Shield III)" to reflect that these are the final pieces of equipment per tier.

---

**Missing period in Extra Perk Info/Minimal Perk Info tooltip**
Category: Quality of Life

![image](https://user-images.githubusercontent.com/106824371/186776565-d90ad5f2-5ffc-4dba-ba5e-0c424fd2b0d8.png)

Missing period is inconsistent with most other tooltips.

---

**Missing period in Block Big Popups/Allow Big Popups tooltip**
Category: Pop-ups and Alerts

![image](https://user-images.githubusercontent.com/106824371/186776939-a14d3f62-8d97-4e02-be44-a860e902e55c.png)

Missing period is inconsistent with most other tooltips.

---

**Pop-ups vs. Popups**

You may have just noticed alongside me that Popups/Pop-ups is spelled differently between the Settings category and the individual setting. I do think that the non-hyphenated spelling looks better.

---
**Missing period in Roman Numerals/Arabic Numerals tooltip**
Category: Layout

![image](https://user-images.githubusercontent.com/106824371/186777941-6dbb710b-1a55-44b5-90c0-2611067bb809.png)

Missing period is inconsistent with most other tooltips.

---

**Missing period & inaccurate name(?) in Extra Map Buttons/Less Map Buttons tooltip**

![image](https://user-images.githubusercontent.com/106824371/186778214-be2eccf9-2538-4aa9-b7b7-0fd4cd88dacb.png)

Missing period is inconsistent with most other tooltips.

Perhaps "Less Map Buttons" should be renamed as "No Map Buttons"? It makes more semantic sense to me, as toggling it removes/adds all 4 buttons, not just some.

---

**Missing period in MAZ tooltip**
Category: Other

![image](https://user-images.githubusercontent.com/106824371/186780216-193a0ffd-3c16-4fe0-85f9-d2acd964c086.png)

Missing period (after **Z**) is inconsistent with most other tooltips.

---

**Missing period in Time Warp Config tooltip**
Category: Other

![image](https://user-images.githubusercontent.com/106824371/186780665-d0b22620-8ca1-4379-8caa-598a94d61f84.png)

Missing period (after **Settings -> Other**) is inconsistent with most other tooltips.

**Comment by Trimps** [comment]
Thank you so much for the detailed write up! I agree with all of these except the point about "Extra Map Buttons", as there are map buttons on the left side of the map grid as well that aren't controlled by this setting.

Everything else has been added to the 5.9.0 Test Server!
