### ISSUE TITLE
Continuity error in tooltip for Healthy enemies

### ISSUE THREAD

**Issue by bddbdwbej** [Trimps/bug-tracker#127]
The tooltip reads "It will also drop 45% of the Helium you would normally get from completing this Zone." where it should be "**65%**" after obtaining Strength In Health II.
![image](https://user-images.githubusercontent.com/106824371/187051965-97e0d0df-5672-4c28-9569-53d800a49c31.png)

**Comment by Trimps** [comment]
Fixed on the 5.9.0 Test Server, thanks!
