### ISSUE TITLE
Still Magmamancing is outside of prerequisite column(s)

### ISSUE THREAD

**Issue by bddbdwbej** [Trimps/bug-tracker#128]
Still Magmamancing is the only mastery that does not lie in the same column as its prerequisite masteries (Still Rowing II and Magmamancermancy). Given that Void Spec I/II - MotV lie at the bottom of the table, it should be swapped with Mesmer for consistency.
![image](https://user-images.githubusercontent.com/106824371/187052053-020443c2-7076-4399-941f-1bef6b729e70.png)

**Comment by Trimps** [comment]
Fixed on the 5.9.0 Test Server, thanks!
