### ISSUE TITLE
MagnetoShriek active description refers strictly to Improbabilities

### ISSUE THREAD

**Issue by bddbdwbej** [Trimps/bug-tracker#129]
When active, the MagnetoShriek description always says it will fire on the next Improbability, when it fires on Omnipotrimps and (Echoes of) Droupitee as well. This could be amended by simply matching the description to the Zone you're in when activated.

"**MagnetoShriek is currently active and will fire on the next Improbability.**"

"**MagnetoShriek is currently active and will fire on the next Omnipotrimp.**"

"**MagnetoShriek is currently active and will fire on Droupitee.**"

"**MagnetoShriek is currently active and will fire on the Echo of Droupitee.**"

![image](https://user-images.githubusercontent.com/106824371/187089126-b2436885-6656-4133-8912-b6e457949bbb.png)

**Comment by Trimps** [comment]
Fixed on the 5.9.0 Test Server, thanks!
