### ISSUE TITLE
Void Maps filter missing additional info in Message Config window

### ISSUE THREAD

**Issue by bddbdwbej** [Trimps/bug-tracker#130]
Accessed by clicking the gear in the top right of the message log, the Message Config window provides no context for the Void Maps filter when you hover over it. This is the only filter with this issue (that I know of. You may want to check other filters I may not have access to yet).

![image](https://user-images.githubusercontent.com/106824371/187310480-f7737934-f6b3-4858-a73c-dd5437ca1964.png)

**Comment by Trimps** [comment]
Fixed on the 5.9.0 Test Server, along with Runetrinkets, Alchemy, and Seeds. Thanks!
