### ISSUE TITLE
Geneticistassist invalid timer text incorrect

### ISSUE THREAD

**Issue by blackdiamand** [Trimps/bug-tracker#131]
Entering 5001 into GA says "Sorry, all numbers must be less than 5000." But entering 5000 is a valid input. 

The error message should say "Sorry, all numbers must be less than or equal to 5000."

**Comment by bddbdwbej** [comment]
"Sorry, all numbers must be less **than** or equal to 5000.", no?

**Comment by Trimps** [comment]
Fixed on the 5.9.0 Test Server, thanks!
