### ISSUE TITLE
Arabic Numerals do not appear in Achievements menu

### ISSUE THREAD

**Issue by bddbdwbej** [Trimps/bug-tracker#132]
Spires are still labeled with Roman Numerals in the Achievements menu when Arabic Numerals are enabled. I assume this applies to Spires I have not reached yet as well. This is present in the Achievement categories and descriptions.

The achievement names for Spire V/5 wouldn't make much sense with Arabic Numerals enabled, but I suppose that's not something that can be resolved well.

![image](https://user-images.githubusercontent.com/106824371/187788155-15efaacb-f0cf-4ea4-833d-57790322bf6d.png)
**Achievement categories**

![image](https://user-images.githubusercontent.com/106824371/187816157-fbca57d1-0beb-4f19-ba5b-9ca918883da5.png)
**Achievement description for Toxic Treader; this is present in all other Spire II/2+ achieves**

**Comment by Trimps** [comment]
Fixed on the 5.9.0 Test Server, thanks!
