### ISSUE TITLE
Helium challenges need to say "during this portal"

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#135]
Balance challenge:
> Completing Zone 40 with this challenge active will grant an additional 100% of all helium earned up to that point. This challenge is repeatable!

change to
> Completing Zone 40 with this challenge active will grant an additional 100% of all helium earned up to that point during this portal. This challenge is repeatable!

New players find this confusing and think ALL helium is multiplied

**Comment by Trimps** [comment]
Added to the 5.9.0 Test Server, thank you!
