### ISSUE TITLE
C^3 Challenge description partly unreadable contrast

### ISSUE THREAD

**Issue by kabale7** [Trimps/bug-tracker#147]
**Describe the bug**
In the C^3 Challenge description showing the progress: The dark green text on blue background is very hard to read, please change the color of the darkgreen text to a much lighter and more readable color.

**To Reproduce**

1. Go to '...' U2 Universe, while C3 challenge is running (in this case unbalance)
2. Click on '....' Portal / Current Challenge / 

**Expected behavior**
The color of the text in C3 Challenge should be changed to a light color (light green or white), or make sure the background doesnt change to a color that is very close in contrast to the text written on it.

**Screenshots**
![C3 challenge unreadable text](https://user-images.githubusercontent.com/115544950/195067062-130e6232-c1a1-43e8-b36e-9917be6e2509.png)

**Environment (please complete the following information):**
 - OS version (Windows 10, 11? Linux?) Windows 7 
 - Game Version (are you playing on the web, or on Steam)? V5.8.0 kongregate
 - If you're playing on the web, which browser are you using? [e.g. Chrome, Firefox, Safari] Firefox 105

**Additional context**

**Comment by Trimps** [comment]
Fixed with 5.8.1, thanks!
