### ISSUE TITLE
On the Spire failure log message, mention the cell the player has lost the Spire on

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#158]
**Is your feature request related to a problem? Please describe.**
Players would like to know how far into the spire they died if they weren't actively looking

**Describe the solution you'd like**
Change the following log message
> You're not yet ready. Maybe you'll be of use in the next lifetime.    

to    
> You're not yet ready. Maybe you'll be of use in the next lifetime. (Cell X)    

where X is the cell the player was at when the message was sent

**Comment by Trimps** [comment]
Added to 5.9.0 test server, thanks!
