### ISSUE TITLE
Scruffy Level 11 Ability is missing the word, "more"

### ISSUE THREAD

**Issue by CMMMurphy** [Trimps/bug-tracker#159]
Scruffy's level 11 text sounds like it conflicts with Tenacity's text. Adding the word, "more" will make it much more clear. 

From: "Start each zone with 15% of last zone's Tenacity time already applied." 
To: "Start each zone with 15% **more** of last zone's Tenacity time already applied."

For reference, Tenacity says, "When you clear a Zone, you carry 50% of the time you spent last Zone (up to 2 hours) with you to the new zone." 

![Screenshot 2022-10-26 084930](https://user-images.githubusercontent.com/116745380/198074159-b8463792-6f89-4a6b-8c6d-7a3a046cd7ad.png)

**Comment by Trimps** [comment]
Added to the 5.9.0 Test Server, thank you!
