### ISSUE TITLE
Observation tooltip incorrect implies that there is a chance, per level.

### ISSUE THREAD

**Issue by CMMMurphy** [Trimps/bug-tracker#162]
Please correct the tooltip on the Observation Perk. It currently reads: 

- "...for each level of this perk, your trimps will gain a chance per zone cleared above z100 to find a runetrinket. ..."

The text, as written, implies that you have a separate chance for each level of this perk, for each zone that you clear above z100. In other words, the text says that if you have level 3 of Observation, with ~5% chance at z130, then when you clear z130, it will make a random check, three times, where each check has a 5% of finding a runetrinket. 

That's not what happens. In reality, the chance goes up by 50% (as stated later in the tooltip) for each level of the perk. And you only get ONE chance to find a runetrinket, per zone, based on your chance. Here's a stronger way to state what actually happens: 

- "... This perk grants your trimps the chance to find a runetrinket each time you clear a zone above z100. ..."

Thanks for your consideration.
Curtiss.

PS - thanks for making one of the greatest Idle games ever made.  I hope it provides you enough income to make it worth continuing for years to come. I've certainly done my part to that end ;)

**Comment by Trimps** [comment]
This is now fixed on the 5.9.0 Test Server, thank you for the report!
