### ISSUE TITLE
Heirlooms imply Nu is spent with this wording, despite that not being true.

### ISSUE THREAD

**Issue by SereKabii** [Trimps/bug-tracker#163]
![image](https://user-images.githubusercontent.com/63935471/198903481-1e9e040e-6f63-497b-baa0-d33bda7865a1.png)
this could be changed from spent/unspent to allocated/available instead or something similar, to make it less contradictory with how it actually works. (the masteries and other bonuses to nu percentile would likely need to be changed to match.)

**Comment by Trimps** [comment]
Added to the 5.9.0 Test Server, thank you!
