### ISSUE TITLE
Hypothermia doesn't block perk string import properly

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#167]
**Describe the bug**
Hypothermia challenge doesn't allow modifying your perks. However it appears you can still change your perks by importing a perk string from e.g. Surky. Not only that, but you're also able to remove perks, and doing so doesn't use up a respec, so in effect you can respec as many times as you want in a run.

**To Reproduce**
1. Export to surky
2. Mess with your perks, up some, lower some
3. Go to View Perks screen and import a perk string
4. Enjoy infinite respecs

**Expected behavior**
Importing a perk string should not be allowed

**Comment by Trimps** [comment]
Fixed with 5.8.1, thank you!
