### ISSUE TITLE
Berserk does not work as described

### ISSUE THREAD

**Issue by Quiaaaa** [Trimps/bug-tracker#169]
The description states
> Every time your Trimps attack they have a 5% chance to become Frenzied

The actual behavior is such that you get 
> 5% chance of setting your frenzy stacks to 1, only when you have 0 frenzy stacks
> 1 stack on killing an enemy

**Fixed text**
> Travel to a dimension filled with lots of mild annoyances, sure to drive your Trimps berserk. All enemies in this dimension have 50% more attack and health. Every time your Trimps attack they have a 5% chance to become frenzied, and each kill while frenzied will increase your frenzy, up to 25 stacks. While frenzied, kills heal your Trimps for 1% of max health, and each stack adds +50% attack and -2% max health. If a frenzied group dies or is abandoned, your Trimps gain a permanent Weakened stack, reducing health by 4.99% per stack when outside of frenzy. If weakened stacks reach 20, Trimps can no longer become frenzied. Due to this dimension's annoying nature, the Angelic Mastery does not work.

**Additional context**
  ```
          enemyDied: function(){
                if (this.frenzyStacks <= 0) return;
                var oldBonus = this.getHealthMult();
                this.frenzyStacks++;
                if (this.frenzyStacks > 25) this.frenzyStacks = 25;
                if (game.global.soldierHealth > 0){
                    game.global.soldierHealth += (game.global.soldierHealthMax * 0.01);
                    this.updateHealth(oldBonus);
                }
                this.drawStacks();
            },
            attacked: function(){
                if (this.frenzyStacks > 0) return;
                if (this.weakened >= 20) return;
                var oldBonus = this.getHealthMult();
                if (Math.floor(Math.random() * 100) < 5) this.frenzyStacks = 1
                else return;
                this.updateHealth(oldBonus);
                this.drawStacks();
            },
```

**Comment by Trimps** [comment]
Fixed with 5.9.0, thank you!
