### ISSUE TITLE
Alerting setting should also mention that icons are blue in dark theme 

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#17]
**Describe the bug**
Alert icons are blue in dark theme, the description should say something like "(...)yellow alert icons (blue in dark theme) when unlocking something new"

**Screenshots**
![image](https://user-images.githubusercontent.com/51026936/171232878-d509667d-c6bb-4d53-8658-f482208638ec.png)

**Comment by Trimps** [comment]
Fixed in 5.7.2!
