### ISSUE TITLE
Equality button in time warp always starts green even if Equality Scaling is off

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#170]
**Describe the bug**
Equality button in time warp always starts green even if Equality Scaling is off

**To Reproduce**
1. Turn off equality
2. Save
3. Close the game for 5+ minutes
4. Equality button in time warp is green. After clicking the button it remains green (now equality is turned on). Clicking it again makes it red (equality is off)

**Expected behavior**
Initial state of the button in time warp needs to be based around current equality state

**Comment by Trimps** [comment]
Fixed with 5.8.1, thanks!
