### ISSUE TITLE
Nursery autostructure does not work on eradicated

### ISSUE THREAD

**Issue by Molodude** [Trimps/bug-tracker#173]
**Describe the bug**
Autostructure does not rebuy nurseries up to max on the eradicated challenge when nurseries decay.

**To Reproduce**
1. Run Eradicated challenge
2. Enable nurseries in autostructure with a cap.
3. Advance zone
4. Nurseries decay, but autostructure does not rebuy back to the cap as expected, even though more nurseries are affordable.

**Expected behavior**
Autostructure should repurchase nurseries.

**Additional context**
In the "buyAutoStructures" function, the game only subtracts from the nursery count if the zone is above 230. As a result it does not think any nurseries have decayed in eradicated which has magma enabled but is pre-230.

**Comment by Trimps** [comment]
This was fixed in 5.8.1, thank you for the report!
