### ISSUE TITLE
Void Spec description innaccuracy

### ISSUE THREAD

**Issue by SereKabii** [Trimps/bug-tracker#176]
![image](https://user-images.githubusercontent.com/63935471/204109844-9a1fbf02-4dff-4907-b14f-f964b26fea74.png)
Void Specialization indicates that it's based on your highest cleared zone last portal, not your highest reached zone. That is incorrect and contradictory with the rest of the description.
![image](https://user-images.githubusercontent.com/63935471/204109883-1a62ee9a-a6ec-4338-b1c7-bb0d9723a166.png)
As you can see both from this second half of the description and its value, it is, in fact, based on zone reached.
As Scruffy's L3+1 bonus seems to have correctly worded this mechanic, you could use it as the basis for rewriting these descriptions.

**Comment by Trimps** [comment]
Fixed on 5.9.0 Test Server, thanks!
