### ISSUE TITLE
"Overhealed" Enemies During Time Warp (and a suggestion to help pinpoint the issue

### ISSUE THREAD

**Issue by 5h3i1ah** [Trimps/bug-tracker#178]
**Describe the bug**
During Time Warp, sometimes an enemy will have orders of magnitude more health than its max, resulting in progress being completely halted.

**To Reproduce**
1. Use Time Warp. Maybe under certain conditions? I triggered it on Linux when my computer went to sleep and later woke up, and when doing that, Trimps runs without Time Warp for a few seconds before Time Warp starts.
2. When Time Warp ends, sometimes the enemy will have a massive amount of HP.

**Expected behavior**
Enemies always have normal HP, Time Warp does not halt progress

**Screenshots**
![image](https://user-images.githubusercontent.com/17099837/204593646-4e0dfba9-786b-4713-81d7-7771d887375c.png)

**Environment (please complete the following information):**
 - EndeavourOS (Linux)
 - Steam, 5.8.0

**Additional context**
I think some error checking during time warp would be useful for the time being. Save what tick you start each enemy on, and if progress slows to a crawl on an enemy, check to see if its current HP is above its maximum. If it is, send a log of what happened to Greensatellite, turn back the time warp to when you started on that enemy, manually set its current HP to its max, and resume Time Warp. Maybe also run the same check when time warp ends, in case the "slows to a crawl" thing isn't triggered on an overhealed enemy before Time Warp ends.

**Comment by Trimps** [comment]
Added some extra checks for this to the 5.9.0 Test Server, thanks!
