### ISSUE TITLE
Karma (daily modifier) doesn't affect seconds of production loot 

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#18]
**Describe the bug**
The daily modifier Karma
![image](https://user-images.githubusercontent.com/51026936/171234161-0106c7fb-0c93-4d29-9ace-9e9e07b84f5a.png)
doesn't affect seconds of production loot, e.g. Bone Shrine, caches, Jestimp, Chronoimp

**Comment by Trimps** [comment]
Fixed in 5.7.2!
