### ISSUE TITLE
U2 z275+ heirloom bracket applies from z250+

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#180]
**Describe the bug**
The U2 z275+ heirloom bracket (50% / 50%) applies starting from z250+
The game jumps right away from the z225-z249 bracket to the z275+ bracket, skipping the z250-z274 bracket.

**To Reproduce**
`for (let i = 0; i < 200; i++) { createHeirloom(250, false, false, false); }`
You will receive a 50/50 split of haz/enigmatic
`for (let i = 0; i < 200; i++) { createHeirloom(249, false, false, false); }`
You will receive a 10/90 split

**Expected behavior**
Either the z250-z274 split should be applied correctly, or should be removed and z275+ split brought down to z250+ to fix the inconsistency

**Comment by Trimps** [comment]
Fixed with 5.8.1, thanks!
