### ISSUE TITLE
(u2 z150+) Some feat unlock zones are inconsistent

### ISSUE THREAD

**Issue by SereKabii** [Trimps/bug-tracker#186]
**Describe the bug**
For the Alchemy, Glass and Hypothermia challenges, their feats unlock at unexpected zones. Particularly, Alchemy unlocks at z150, and Glass and Hypothermia unlock at z176.

**To Reproduce**
1. Have a hze between 150 and 154 or of exactly 175
2. Click on the achievements button
3. Scroll down to feats

**Expected behavior**
Like usual, they should unlock at the same zone you unlock the challenge at.

**Environment (please complete the following information):**
 - Steam port
 - Version 5.8.1

**Comment by Trimps** [comment]
Fixed on the 5.9.0 Test Server, thanks!
