### ISSUE TITLE
Golden Maps +100% loot bonus does not apply to existing maps

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#187]
**Describe the bug**
Golden Maps +100% loot bonus does not apply to existing maps. The tooltip claims it should, so either the tooltip is wrong or the behavior is wrong:
> You are about to purchase Golden Maps for 20 bones. All of your current and future maps will gain +100% loot added to their normal loot roll until your next Portal. Is this what you wanted to do?

**To Reproduce**
1. Make a few maps
2. Buy Golden Maps
3. Go back to map chamber and make a few more maps
4. Unique maps and existing created maps don't have increased loot, but new maps do

**Expected behavior**
Existing maps should get +100% to loot upon purchase, or the tooltip should be adjusted

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/51026936/209447883-22101287-bf2a-4969-8495-4a696f307647.png)

After:
![image](https://user-images.githubusercontent.com/51026936/209447918-9d9e74e0-f1de-4f58-a783-fb9e2002d9c1.png)

**Comment by Trimps** [comment]
Fixed on the 5.9.0 Test Server, thanks!
