### ISSUE TITLE
Make it so 100%+ Runetrinket chances give you a chance to proc trinkets twice

### ISSUE THREAD

**Issue by SereKabii** [Trimps/bug-tracker#189]
**Is your feature request related to a problem? Please describe.**
The core concept behind Observation was always that the more levels you have on it, the more trinkets you get. That ends up not being the case in practice for lategame runs, as early as ~z200 obs 14 you'll get chances as high as 150% which don't matter, and further levels will barely matter as well.
This straight up causes capping out trinkets to be completely unreasonable in the current iteration of the Trimps meta.

**Describe the solution you'd like**
See title.

**Describe alternatives you've considered**
Maybe dailies could have an effect on trinket drop? I'd love this in the early observation meta since it'd take a bit of the spotlight away from spamming alchemy, but application could be somewhat wonky on the radon dailies meta.

**Comment by Trimps** [comment]
This has been added to the 5.9.0 Test Server, thanks for the suggestion!
