### ISSUE TITLE
Void map completion text in c2s (likely c3s as well) has an extra space.

### ISSUE THREAD

**Issue by AugustusArgento** [Trimps/bug-tracker#191]
I noticed this issue where the void map completion text has an extra space before the ending period. This is likely because it is meant to have the helium/radon gain following it (eg "...to the world with [whatever]."), but since it was completed in a c2, there was no accompanying text for the resource gain, leaving off the string with a space at the end. A solution that would probably work (if I'm understanding the cause of the issue correctly) would be to move that space from the standard void map text to the resource part, since then if there is no helium/radon gain, there won't be a space at the end of the standard text.
![image](https://user-images.githubusercontent.com/93684219/210902030-eac83230-88ef-41aa-addf-d8adc1b4ad10.png)

**Comment by Trimps** [comment]
Fixed on 5.9.0 Test Server, thanks!
