### ISSUE TITLE
Archaeology automator unlocks at wrong zone.

### ISSUE THREAD

**Issue by Molodude** [Trimps/bug-tracker#193]
**Describe the bug**
The archaeology automator option in settings unlocks if your hze is 95, when it should unlock at 90. It seems it was forgotten to be moved when archaeology was changed from 95 to 90.

**To Reproduce**
1. Have a hze below 95 but archaeology unlocked.
2. Check settings -> other
3. Archaeology automator setting is missing.

**Expected behavior**
Archaeology automator should be visible with hze 90, not 95.

**Comment by Trimps** [comment]
Fixed on 5.9.0 test server, thanks!
