### ISSUE TITLE
Certain pinned achievements do not fit their box in the message log.

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#194]
**Describe the bug**
Certain pinned achievements do not fit their box in the message log. On a 1080p monitor, these achievements are:
- When The Wild Things Are (Total Portals)
- The Tortoise and the Bugs (Feats)
- Residential Development (Real Estate)
- Trimpsponential Growth (Trimps Owned)
- Through the Unknown (U2 Zone Progress)
- To Infinity and Beyond (Real Estate)
- A Trimp Through Time (Total Portals)
- You're Doing it Wrong (Feats)
- Transcendental Trimps (Trimp Damage)
- A Time Like No Other (Total Portals)
- Couple-Cent Comfort (Shielded)
- Unsatisfied Customer (Feats)
- Neverending Journey (U2 Zone Progress)
- Acquaintance of Bots (Speed: Bionic)
- Obsidian Obliterator (Zone Progress)
- Master of Universes (Zone Progress)
- Too Cool for Helium (Real Estate)
- All Said and Radone (Radon Collection)
- Universal Destroyer (U2 Zone Progress)
- Bringer of Progress (U2 Zone Progress)
- Collector of Shinies (Gem Collection)

Having been collected manually, this may not be an exhaustive list.

**To Reproduce**
1. Go to Achievements
2. Click on one of the aforementioned achievements to pin one
3. Go back
4. Observe issue

**Expected behavior**
Achievement titles should fit single line

**Screenshots**
![image](https://user-images.githubusercontent.com/51026936/214177530-a48aca1e-537d-4021-9ed3-dc907849db8f.png)

**Comment by Trimps** [comment]
Fixed on 5.9.0 test server, thanks!
