### ISSUE TITLE
Trapper² does not mention that any bonuses that cause housing to come prefilled with Trimps will not work

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#24]
Regular Trapper description:
> Travel to a dimension where Trimps refuse to breed in captivity, teaching yourself new ways to take advantage of situations where breed rate is low. Clearing 'Trimple Of Doom' (33) with this challenge active will return your breeding rate to normal. **Note that any bonuses that cause housing to come prefilled with Trimps will not work in a dimension where Trimps cannot breed**

This is also true in Trapper², which does not mention this part.

Trapper² should also mention:
> Note that any bonuses that cause housing to come prefilled with Trimps will not work in a dimension where Trimps cannot breed

**Comment by Trimps** [comment]
Fixed in 5.7.2!
