### ISSUE TITLE
Pausing in last 2 battles stops fighting upon map restart

### ISSUE THREAD

**Issue by bddbdbwej** [Trimps/bug-tracker#27]
**Describe the bug**
Only occurs with AutoFight off. When you pause and then unpause the game (time interval betwen the two does not seem to matter) while fighting one of the last two battles in a map, your soldiers will stop fighting when it restarts. This does not occur when you pause at any point before this threshold.

This occurs even when clearing Void Maps, where maps are not *technically* being repeated.

- Occurs independent of map size (same behavior with 72-cell and 25-cell maps)
- Occurs independent of special modifiers (toggling Prestigious or Fast Attacks has no effect)
- Occurs in unique maps (tested with Bionic Wonderland X and Imploding Star)

**To reproduce**
1. Enter a map and turn AutoFight off.
2. Run it to a point where you will clear the map within 2 battles, including Overkill.
3. Pause.
4. Unpause.
5. Clear the map.

Your soldiers will be sitting at the start of the map, not fighting.

**Expected behavior**
Soldiers keep fighting upon map restart regardless of pauses within the map.

**Screenshots**
Successful pause state with +2 Overkill
![image](https://user-images.githubusercontent.com/106824371/171960649-09cff179-1b75-4c6c-b3b2-68bac5ab8d16.png)
Successful pause state with no Overkill
![image](https://user-images.githubusercontent.com/106824371/171961590-2f19f50a-910e-4a87-bfa8-649725184213.png)
Successful pause state in Void Map with +2 Overkill
![image](https://user-images.githubusercontent.com/106824371/171965484-0d0289b9-5433-4ddc-a4b8-415c34d0f256.png)

**Environment**
Steam, Microsoft Edge, and Google Chrome on Windows 10 (untested elsewhere)

**Additional context**
Not sure what's happening here. Maybe pausing clears some sort of trigger that tells the game to keep fighting after the next battle??  Strange in its thin window.

**Comment by grabz-dev** [comment]
What a weird problem. I gave it a try and indeed this is something that happens. Interesting find.

**Comment by Trimps** [comment]
Fixed in 5.7.2!
