### ISSUE TITLE
Scryhard 1 keeps 2x damage buff even if you switch to X or D stance within the same corrupted cell

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#3]
**Describe the bug**
Scryhard 1 keeps 2x damage buff even if you switch to X or D stance within the same corrupted cell. 
The damage breakdown doesn't show that being the case.
![image](https://user-images.githubusercontent.com/51026936/171067615-133aac8b-163f-4efd-b05a-7c2d21bbd05d.png)
![image](https://user-images.githubusercontent.com/51026936/171067617-f704312a-c88f-4d10-8243-62adc11e2c1e.png)

**Comment by Trimps** [comment]
This was a display bug only, but is fixed in 5.7.2!
