### ISSUE TITLE
Importing a save that doesn't have Gardens unlocked while on a save that does lets that save make Garden maps

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#31]
**Describe the bug**
Importing a save that doesn't have Gardens unlocked while on a save that does have Gardens unlocked, allows the imported save to make Gardens maps. In addition, if you then save a map preset with Gardens on, save and refresh, the map preset is loaded with an empty biome selector:
![image](https://user-images.githubusercontent.com/51026936/172031095-1eb9ee7b-6b1a-43a1-95d1-8b3b5bd1321d.png)
And lets you make undefined maps:
![image](https://user-images.githubusercontent.com/51026936/172031103-c620bb61-0f3e-464b-ac5a-35b8c51afe50.png)

**To Reproduce**
1. Import a save with Gardens unlocked
2. Import a save without Gardens unlocked - Gardens are unlocked (bug 1)
3. Save a map preset with Gardens, then save and reload
4. Your bugged map preset can make undefined maps

**Comment by Trimps** [comment]
Fixed in 5.7.2!
