### ISSUE TITLE
Add a tooltip when hovering over the He/hr value explaining what it is and how it's calculated

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#35]
**Is your feature request related to a problem? Please describe.**
New players sometimes confuse what the Helium/hr value is trying to tell them, sometimes mistaking it with passive production.

**Describe the solution you'd like**
Show a tooltip (similar to the ones you get when hovering over structures or masteries) when hovering over He/hr, that explains that the value is **not production** but an estimate based on gained drops, and explain that it is calculated by taking the player's current helium and dividing it by the run timer.

**Comment by Trimps** [comment]
Added in 5.7.2
