### ISSUE TITLE
Void map message / log config option.

### ISSUE THREAD

**Issue by Molodude** [Trimps/bug-tracker#36]
Would like to be able to have void maps show up in the message boxes, but this currently requires gems and fragments to also be on.

Would like there to be a separate checkbox for void maps, as they are currently lumped under "secondary", which means it is shared with gems/fragments. Void maps seem different enough from gems/fragments to warrant an additional setting.

**Comment by Trimps** [comment]
Added in 5.7.2, thanks for the suggestion!
