### ISSUE TITLE
icon-star-half-empty doesn't match other Frenzy star icons, should instead be icon-star-half

### ISSUE THREAD

**Issue by 5h3i1ah** [Trimps/bug-tracker#37]
`icon-star-full`
![image](https://user-images.githubusercontent.com/17099837/172233837-d93083d9-1723-406e-a613-654e217c5847.png)
`icon-star-empty`
![image](https://user-images.githubusercontent.com/17099837/172233862-dacdb7fa-8bce-4b6d-a91d-6fb921c28079.png)

`icon-star-half-empty`, currently used. It is slightly smaller and more rounded, causing a visible pixel shift in the battle icons.
![image](https://user-images.githubusercontent.com/17099837/172233885-93a3b08e-a928-4044-b2c6-394de963f13c.png)

`icon-star-half`, the better alternative, identical shape and size to the `full` and `empty` stars.
![image](https://user-images.githubusercontent.com/17099837/172233963-85e63868-7c7f-4cad-a53f-6bde9294131e.png)

Located in config.js, within Frenzy's drawStacks.

**Comment by Trimps** [comment]
Fixed in 5.7.2!
