### ISSUE TITLE
Everything about Storm challenge's text

### ISSUE THREAD

**Issue by 5h3i1ah** [Trimps/bug-tracker#41]
The original Storm challenge description is kinda clunky and difficult to process, plus it has multiple inconsistencies with other text in the game, so I'm proposing a rewrite to it.

Original description:
> Travel to a dimension that storms year-round. Trimps gain Storm stacks after every attack, damaging them for 5% of their max hp per stack. Enemies gain Cloudy stacks after every attack. Every 5 Cloudy particles causes a Stormcloud on that enemy, causing them to gain max hp and damage, and take extra damage from gamma bursts. Cloudy stacks stick around after bad guys die, and each new group of bad guys start with a Cloudy stack for each Stormcloud on the previous enemy. Cloudy stacks cannot accrue and Stormclouds have no effect in maps, but Trimps in maps have -0.05% attack per Cloudy stack on the enemy. Defeating an enemy in a map will remove 1 Cloudy stack. Completing **Z105** with this Challenge active will return the Dimension to normal [and reward you with a brand new building to help with the weather!].

Rewrite:
> Travel to a dimension that storms year-round. Trimps gain Storm stacks after every attack, damaging them for 5% of their max health per stack. Enemies gain Cloudy stacks after every attack. Every 5 Cloudy stacks creates a Storm Cloud on that enemy, causing them to gain max health and damage but take extra damage from Gamma Bursts. When a Bad Guy dies, any Storm Clouds it had before dying are transferred to the next Bad Guy in the form of Cloudy stacks. In maps, Cloudy stacks cannot accrue and Storm Clouds have no effect, but Trimps have -0.05% attack per Cloudy stack on the enemy. Defeating an enemy in a map will remove 1 Cloudy stack. Completing **Z105** with this Challenge active will return the world to normal [and reward you with a brand new building to help with the weather!].

Additional changes:
- In the z105 text, "eachother" isn't a word, it should be "each other" ![image](https://user-images.githubusercontent.com/17099837/172715535-7d02f981-ccc2-4f43-818c-306a4566815d.png)
- The description calls them Storm stacks, but the stack tooltip calls them Static. One of these needs to be corrected. ![image](https://user-images.githubusercontent.com/17099837/172715743-d0f3ad37-378d-4154-a9ad-8adc1e011907.png)
- Sometimes the tooltip shows a decimal point for the damage taken. This should probably be prettified to have no decimal places. ![image](https://user-images.githubusercontent.com/17099837/172716040-c85aeff9-4172-4338-a13b-77e382647536.png)
- Change "Stormcloud" to "Storm Cloud" in the Cloudy and "Stormcloud" tooltips. ![image](https://user-images.githubusercontent.com/17099837/172716505-f7c573f0-9a3b-4d79-9200-0d0143aff4cc.png)
- Change this text to "This enemy is engulfed by the storm! It has [ ]% extra health AND [ ]% extra attack, BUT IT takes [ ]% extra damage from Gamma Bursts." (capitalization indicating changed text) ![image](https://user-images.githubusercontent.com/17099837/172716702-c82582cb-871e-44d6-a565-21b9453bed99.png)

**Comment by Trimps** [comment]
These changes have been made for 5.8.0, thanks a ton!
