### ISSUE TITLE
Incorrect message when attempting to move on from unique map

### ISSUE THREAD

**Issue by bddbdwbej** [Trimps/bug-tracker#50]
You get this message when attempting to enter a map while your soldiers are inside another map:

![image](https://user-images.githubusercontent.com/106824371/173196470-8caa2627-be6b-4578-8302-725d05ec23c9.png)

This is accurate when the currently occupied map is 'regular', but should be changed to "You must finish or **abandon** your current map before moving on." when the currently occupied map is unique (e.g. Bionic Wonderland, The Prison). This reflects the actual options available to you.

**Comment by Trimps** [comment]
Fixed on the 5.9.0 Test Server, thanks!
