### ISSUE TITLE
Display for 'Born Imploded' and Spire Spirer' feats get cut off (1920x1080 on Steam)

### ISSUE THREAD

**Issue by Caerulo** [Trimps/bug-tracker#59]
The text display for 'Born Imploded' and 'Spire Spirer' when progress state is at 'Too Slow' overruns the UI panel and gets cut off. (1920x1080 resolution on Steam)
![image](https://user-images.githubusercontent.com/17349659/174113945-77b462b0-20ba-48c1-b961-6afb17a5b286.png)
![image](https://user-images.githubusercontent.com/17349659/174113991-90370a10-5d67-43b2-9c5d-37908c0aaab2.png)

**Comment by Quiaaaa** [comment]
This is an AT specific issue, as it adds the 'seconds' property to the time.

**Comment by Caerulo** [comment]
Apologies, did not test on a clean version before submitting this issue, closing this
