### ISSUE TITLE
Bone Portal button does not refresh the bone count when receiving 20 bones from a Spire clear

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#6]
**Describe the bug**
When receiving the 20 bones from a spire clear, the player receives the bones immediately, but it takes until game refresh or next Skeletimp kill for the Bone Portal button to refresh. This can cause confusion that the bones either aren't received or are delayed.

**Comment by Trimps** [comment]
Fixed in 5.7.2!
