### ISSUE TITLE
Autojobs can over-hire trimps when miners unlock

### ISSUE THREAD

**Issue by Quiaaaa** [Trimps/bug-tracker#63]
**Describe the bug**
Auto jobs hires more trimps than are available to work, causing breeding to completely stop until the player realizes what's going on and fires them manually.

**To Reproduce**
1) have a save with autojobs enabled, and without autostructure unlocked (no auto-filling buildings) 
2) Build some amount of huts and Houses, so that Trimps owned are substantially lower than max Trimps
3) Unlock miners via zone progress.
3) Game allocates too many workers to miners to balance ratios, trimps stop breeding.

**Expected behavior**
Autojobs should only hire trimps if they are free to work, and never put the number of breeding trimps to 0, and definitely not negative.  I'm pretty sure this check exists for normal hiring,

**Screenshots**
![image](https://user-images.githubusercontent.com/96918270/174419484-be7ef1be-e765-4af2-b5e7-65db5940f976.png)

**Additional context**
Paused save just before the bug happens
[minerallocationbug.txt](https://github.com/Trimps/bug-tracker/files/8932837/minerallocationbug.txt)

**Comment by Trimps** [comment]
Fixed in 5.8.0, thank you!
