### ISSUE TITLE
Option to display equipment prestige tiers in Arabic numberals instead of Roman numerals

### ISSUE THREAD

**Issue by Caerulo** [Trimps/bug-tracker#65]
**Is your feature request related to a problem? Please describe.**
While Roman numerals can be fine for small numbers (e.g. masteries), when the values become large it becomes difficult to comprehend quickly. (eg. the mental effort required to understand LXXVIII is much greater compared to 78) It is also difficult to compare equipment prestige tiers (eg. comparing VIII with VII , vs 7 with 8)

**Describe the solution you'd like**
An option to change equipment prestige tier display to Arabic numerals

**Comment by Trimps** [comment]
Added to 5.8.0, thanks!
