### ISSUE TITLE
Core RNG and frozen castle RNG seeds aren't saved between portals

### ISSUE THREAD

**Issue by pearbear321** [Trimps/bug-tracker#68]
I've been told that game.global.coreSeed and game.global.bestHeirloomSeed are supposed to be saved between portals like game.global.heirloomSeed and game.global.heirloomBoneSeed but a new value is generated for them each portal.

This makes them easier to manipulate by portalling repeatedly until you get a desirable seed.

I have no idea what the actual intended behavior for these seeds is, so if they're already working at intended please ignore.

**Comment by Trimps** [comment]
Fixed for 5.8.0, thanks!
