### ISSUE TITLE
Show a tooltip on empty heirloom slots / Heirloom Help

### ISSUE THREAD

**Issue by Quiaaaa** [Trimps/bug-tracker#72]
**Is your feature request related to a problem? Please describe.**
Early players get confused about how to equip heirlooms. Many games use a slot-based equip method, ie click on the slot,and it pulls up the possible equipment, and there's no indication of what they player is doing wrong if they try to repeatedly click on the empty slot.

**Describe the solution you'd like**
Add a tooltip on mouse-over of an empty Heirloom slot that says 'Click on a Carried or Temporary Heirloom to Equip it" or something similar. 

The Help text can be cleared up a bit too, and it could be always shown (maybe in a larger font?  It seems *tiny* to me) if you have an empty shield or staff slot when you open the Heirloom screen.  It's also currently in a weird mix of white, bright red, and dark purple, that is quite hard to read.

**Describe alternatives you've considered**
Changing the 'Nothing' text to be more informative here would work too, and be more in your face than a tooltip.

**Additional context**
I've heard 'can't equip heirlooms' from three different people now, there's also confusion about equipped heirlooms not being safe from deletion on portal if you don't have carry slots.  I've rewritten the Help text and tried to address all the strange questions I've heard lately about Heirlooms. (More carried slots == more equipped heirlooms was a fun one.)

**Current Help Text**
> Heirlooms are powerful items that can drop with a variety of bonuses and a variety of rarities. You will earn one Heirloom every time a Void Map is completed, and you have a better chance to get higher rarities if you complete the Void Map at higher zones. Once you have an Heirloom, you can click the icon below to select it.
> 
>Once you've selected an Heirloom, you can see all of its stats on the right side of this screen. You can click a stat to upgrade or replace it. The currency to upgrade and replace stats, Nullifium, or Nu, can only be gathered by recycling an Heirloom. You can also click on the Heirloom's name on this menu to rename it, or click on the icon to change it! You can upgrade any Staff and Shield to HALF the value of your total earned Nu. Nu is not spent, but dictates how powerful your Heirlooms can be!
> 
>You can only carry a few Heirlooms (other than the two you have equipped) back through the Portal with you when you use it. Any Heirlooms in the "Temporary" section will be recycled for Nullifium on portal. You can purchase slots to Carry more Heirlooms with you through the Portal, but this Nullifium spent this way will be permanently consumed.

**Proposed new Help Text**
> Heirlooms are powerful items that can drop with a variety of bonuses and a variety of rarities. You will earn one Heirloom every time a Void Map is completed, and you have a better chance to get higher rarities if you complete the Void Map at higher zones.
> 
> You can click on the icon of any Heirloom to select it. Once you have selected an Heirloom, you can Equip, Carry, or Recycle it. Only equipped Heirlooms give you stats, and you can only have one of each type of Heirloom equipped at a time. You can click a stat to upgrade or replace it. You can also click on the Heirloom's name on this menu to rename it, or click on the icon to change it.
> 
> The currency to upgrade and replace stats, Nullifium, or Nu, can only be gathered by recycling an Heirloom. You can upgrade any Staff and Shield to half the value of your total earned Nu. Nu is not spent, but dictates how powerful each of your Heirlooms can be.
>
> Your Equipped Heirlooms will always stay with you when you Portal, along with any Heirlooms in your "Carried" slots. Any Heirlooms in the "Temporary" section will be recycled for Nullifium on portal. You can purchase slots to Carry more Heirlooms with you through the Portal, but this Nullifium spent this way will be permanently consumed.

**Comment by Trimps** [comment]
5.8.0 now has a tooltip when hovering over an empty Heirloom slot, and I've also updated the help text! Thank you so much!
