### ISSUE TITLE
Add an option to fade enemies in SpireTD

### ISSUE THREAD

**Issue by Quiaaaa** [Trimps/bug-tracker#74]
**Is your feature request related to a problem? Please describe.**
Spire TD layouts get extremely busy, with up to 5 different visuals based on traps alone. It can be extremely difficult to actually see your layout behind the mess of enemies passing through it.

**Describe the solution you'd like**
An opacity fade option on enemies. I use a tiny css mod.

`.playerSpireEnemy {
	opacity: .2;
}`

**Describe alternatives you've considered**
I've tried hiding them completely, but that feels weird to me. Some form of visual to show that enemies are passing through is important, the current one is just too in your face for me.

**Additional context**
Turn this... 
![image](https://user-images.githubusercontent.com/96918270/176274283-abe6e5a3-6d5c-474b-bf78-896bc7c1f2bd.png)

into this
![image](https://user-images.githubusercontent.com/96918270/176274196-2ccbe359-e8c2-40e4-864d-10af6604ebb6.png)

**Comment by Trimps** [comment]
Done for 5.8.0, thanks for the suggestion!
