### ISSUE TITLE
Ice Enlightenment tooltip should not claim it works "for your entire run"

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#78]
> "While Enlightened, your Trimps gain +2 maximum Overkill cells and +0.25% increased Fluffy Exp per Ice level for your entire run"

The "for your entire run" part is misleading and makes people think they get Overkill before they hit Nature. I'm not sure if this is trying to say that the increased Fluffy Exp applies before zone 230 but Overkill does not, but either way it should be corrected.

**Comment by Trimps** [comment]
Clarified for 5.8.0, thanks!
