### ISSUE TITLE
Fluffy E1L10 ability uses outdated terminology

### ISSUE THREAD

**Issue by Caerulo** [Trimps/bug-tracker#79]
**### Issue**
Fluffy's E1L10 ability description states that it: "Adds 100% to the helium modifier of all Daily Challenges."

This is misleading as daily challenges now multiply more than just helium, and create uncertainty on whether the Fluffy ability only adds to the Helium multiplier, or if it affects the other rewards like Nu, DE and Nature tokens.

**### Solution**
The description for Fluffy's E1L10 ability to be changed to "Adds 100% to the reward modifier of all Daily Challenges."

**Comment by Trimps** [comment]
Fixed, thanks!
