### ISSUE TITLE
Keep the green gradient from Planet Break for longer / Visual Only

### ISSUE THREAD

**Issue by Quiaaaa** [Trimps/bug-tracker#8]
**Is your feature request related to a problem? Please describe.**
The gradient on z60 is really pretty and I am sad that it is only visible for one zone

**Describe the solution you'd like**
Show the gradient for more zones past z60, fading out progressively as you advance. A 5% fade every zone so it hangs around for 20 zones would be a nice 'hey, you monster, you just broke the planet' reminder. And pretty.

**Comment by Trimps** [comment]
Added to 5.8.0! Can't say no to Quia
