### ISSUE TITLE
Buying Microchip 5 briefly produces a bugged tooltip

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#82]
**Describe the bug**
When you buy Microchip 5 and do not move your mouse (so the tooltip doesn't disappear), it updates into a bugged version (presumably trying to pull info from a non existent Microchip 6?)
![image](https://user-images.githubusercontent.com/51026936/177003997-fa7d91a9-a7f9-438a-86c4-3bf52200d2ef.png)

**To Reproduce**
1. Buy Microchip 5
2. Don't move your mouse

**Expected behavior**
The tooltip should probably auto disappear, or say something like "congrats on buying everything"

**Comment by Trimps** [comment]
Fixed for 5.8.0, thanks!
