### ISSUE TITLE
Add number of Bone Shrine charges to its tooltip

### ISSUE THREAD

**Issue by grabz-dev** [Trimps/bug-tracker#85]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/51026936/177494308-4f0d9619-f60b-4cde-a578-2d7aaef67362.png)

**Describe the solution you'd like**
Put somewhere in the tooltip "You have X Bone Shrine charges remaining"

**Comment by Trimps** [comment]
Added to 5.8.0, thanks!
