### ISSUE TITLE
Archaeology feat is unlocked at a higher zone than the challenge itself. 

### ISSUE THREAD

**Issue by Xarec** [Trimps/bug-tracker#88]
**Is your feature request related to a problem? Please describe.**
Patch 5.5.0 moved Archaeology from U2 Z95 to Z90, but the challenge feat is still unlocked at Z95. 

![image](https://user-images.githubusercontent.com/13697777/178224587-8dce8c86-629c-4c63-bb0b-23dd2d765d44.png)
![image](https://user-images.githubusercontent.com/13697777/178224507-998da7d9-a0fb-4f82-a057-d21d3cfc7125.png)

**Describe the solution you'd like**
Lower the unlock requirement for the Archaeology feat "Unassisted" to Z90 to make it consistent with the patch 5.5.0 changes to the challenge itself.

**Additional context**
Wasn't sure whether to label this as a small bug report or enhancement since I don't know whether this is just an oversight or if it is intentional.

**Comment by Trimps** [comment]
Fixed for 5.8.0, thanks!
