### ISSUE TITLE
Rename Core Mod 'Lightning Trap Damage'

### ISSUE THREAD

**Issue by Caerulo** [Trimps/bug-tracker#89]
### Problem
The name for the Core Mod 'Lightning Trap Damage' is misleading and results in players misintepreting it as only affecting the direct damage that lightning traps deal. Although the mod description accurately lists the effects of the mod, the name contradicts the description, potentially confusing players.

### Solution
Rename the core mod 'Lightning Trap Damage' to 'Lightning Trap Effect'

**Comment by Trimps** [comment]
I agree that 'Lightning Trap Damage' is misleading, but I think 'Lightning Trap Effect' is also misleading since the upgrade does also increase Lightning Trap damage. So I've renamed this mod to 'Lightning Trap Power' for 5.8.0 which should be a good catch-all name! 

Thanks for pointing this out!
