### ISSUE TITLE
Change Multitasking upgrade description

### ISSUE THREAD

**Issue by blackdiamand** [Trimps/bug-tracker#91]
The current text:
Teach the most gifted of your Trimps to multitask, allowing 5% of your employed Trimps to breed while they work, and allowing 5% of your unemployed Trimps to help gather resources whenever the town is full.

This text is unclear, since it implies that each upgrade doesn't affect the 5% boost per level.

New text:
Teach the most gifted of your Trimps to multitask, allowing +5% per level of your employed Trimps to breed while they work, and allowing +5% per level of your unemployed Trimps to help gather resources whenever the town is full.

**Comment by Trimps** [comment]
I've adjusted this text for 5.8.0, thanks!
