### ISSUE TITLE
Change Challenge² background color to black when its current zone is at Obsidian

### ISSUE THREAD

**Issue by 5h3i1ah** [Trimps/bug-tracker#92]
**Is your feature request related to a problem? Please describe.**
It can be difficult to distinguish by the challenge button colors exactly which Challenge²s are capped out, as the colors between challenges that are even 50+ zones apart are quite similar in the late game.

**Describe the solution you'd like**
When a Challenge² has been pushed to your current Obsidian zone (or, more specifically, the highest possible bonus with your current Obsidian zone), it should turn black to indicate that that no further bonus can be gained from the challenge at the current time. It's a very stark difference from the usual purples and the direct opposite of the white from challenges at zone 0, and it's thematically fitting as it matches the black color of Obsidian.

**Describe alternatives you've considered**
It could also help in general to increase the contrast between zones near your HZE, perhaps by a... logarithmic color scaling? or something? Because as stated before, at high zones the contrast starts to become very minimal for large zone differences, making it difficult to tell which challenges are further behind than others, so it would be nice to highlight those differences more overall. In the provided screenshot, for example, Toxicity is at z750 while Discipline is at z800, but that's almost impossible to tell. Their colors are `rgb(160,18,160)` and `rgb(154,2,154)` respectively, which are incredibly similar. Even Trapper at z716, with a color of `rgb(164,29,164)`, looks quite similar to Discipline at z800.

**Additional context**
![image](https://user-images.githubusercontent.com/17099837/179438586-313b5b74-48fd-49a0-bb5f-b201663617a4.png)

**Comment by Trimps** [comment]
Added to 5.8.0, thanks for the suggestion!
