### ISSUE TITLE
Visual cue that you have hit c2 cap

### ISSUE THREAD

**Issue by GodNooNoo** [Trimps/bug-tracker#93]
Hi. I think it would be useful to have a way of seeing if you have hit the 60k Challenge 2 cap or not. The game rounds up numbers and displays 60k C2 even when your actual number is less. I had to do math by hand to discover I was still missing 14%.

-Marcin

**Comment by Trimps** [comment]
I've added a congratulatory message to the Challenge Infinity tooltip when you've reached max cap to 5.8.0! Thanks for the suggestion!
