### ISSUE TITLE
Remove button that causes incredible confusion to those that accidentally click it

### ISSUE THREAD

**Issue by Quiaaaa** [Trimps/bug-tracker#96]
**Describe the bug**
![image](https://user-images.githubusercontent.com/96918270/180580443-ec6b125b-150b-4267-bf7e-a915185d5ccb.png)
This button.  It is useless.  All it does is panic people who don't know where their map options went, because it makes no sense to hide them.

**Expected behavior**
Please just kill it.

**Comment by Trimps** [comment]
Removed for 5.8.0!
